global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using SpaceInvadersJA.DataContracts;
global using SpaceInvadersJA.DataContracts.Serialization;
global using SpaceInvadersJA.Models;
global using SpaceInvadersJA.Presentation;
global using SpaceInvadersJA.Services.Caching;
global using SpaceInvadersJA.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
